@startuml
skinparam classAttributeIconSize 0

class Main {
    + {static} main(args: String[])
}

class NBodySimulator {
    - timeStep: double
    - pauseTime: int
    - trace: boolean
    + NBodySimulator(universe: Universe, timeStep: double, pt: int, doTrace: boolean)
    + simulate(): void
    - createCanvas(): void
    - drawUniverse(): void
}

class Universe {
    - numBodies: int
    - radius: double
    + Universe(bodies: Body[], radius: double)
    + update(timeStep: double): void
    + getRadius(): double
    + getNumBodies(): int
    + getBodies(): Body[]
    + getBodyPosition(i: int): Vector
}

class UniverseFactory {
    + {static} createFromFile(fname: String): Universe
    + {static} createCentralConfiguration(numBodies: int, angleVelPos: double): Universe
    + {static} createPlanetaryConfiguration(numPlanets: int): Universe
    + {static} createChoreography(nchoreography: int): Universe
    - {static} randomBetween(min: double, max: double): double
}

class Body {
    - position: Vector
    - velocity: Vector
    - mass: double
    - G: double
    + Body(position: Vector, velocity: Vector, mass: double)
    + Body(position: Vector, velocity: Vector, mass: double, G: double)
    + move(bodies_vector: Vector, timeStep: double): void
    + forceFrom(b: Body): Vector
    + getPosition(): Vector
    + toString(): String
}

' Relacions de composició i agregació
NBodySimulator *--> "1" Universe : universe
Universe --> "1" Body : bodies

@enduml